kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccount: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s/nfs
            - name: NFS_SERVER
              value: 192.168.0.203 # nodes will need nfs-common to access nfs protocol
            - name: NFS_PATH
              value: /mnt/registry2/k8s-data
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.0.203
            path: /mnt/registry2/k8s-data
