apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitea-0
  namespace: gitea
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi