apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: mp-dev.lb-app.cubetiqdns.net
spec:
 secretName: mp-dev.lb-app.cubetiqdns.net
 dnsNames:
 - mp-dev.lb-app.cubetiqdns.net
 issuerRef:
   name: letsencrypt-staging
   kind: ClusterIssuer
