apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: developer-dev
  name: developer-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: developer-dev

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-full-access
  namespace: developer-dev
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-view
  namespace: developer-dev
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: developer-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-full-access
